services:
  bot:
    build: .
    container_name: recipe-bot-local
    restart: always
    env_file: .env
    environment:
      - HTTP_PROXY=http://192.168.1.100:8080
      - HTTPS_PROXY=http://192.168.1.100:8080
      - NO_PROXY=localhost,127.0.0.1
    ports:
      - "8000:8000"
    networks:
      - botnet

networks:
  botnet:
    driver: bridge